version: '3.8'
services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.9-management
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./src/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  producer:
    image: producer
    build:
      context: ./src/producer
      dockerfile: Dockerfile
    environment:
      # APPLICATION
      - CALLBACK_URL=http://localhost:8000/receive/
      - TIMEOUT=4
      # RABBITMQ
      - HOSTNAMERABBIT=rabbitmq
      - RABBITMQ_DEFAULT_USER=local_jobs
      - RABBITMQ_DEFAULT_PASS=password
    ports: 
      - "8000:8000"
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
        - rabbitmq

  consumer:
    image: consumer
    build:
      context: ./src/consumer
      dockerfile: Dockerfile
    environment:
      # APPLICATION
      - MAX_BATCH_SIZE=8
      - BATCH_TIMEOUT=8
      # RABBITMQ
      - HOSTNAMERABBIT=rabbitmq
      - RABBITMQ_DEFAULT_USER=local_jobs
      - RABBITMQ_DEFAULT_PASS=password
    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
        - rabbitmq
